### ISSUE TITLE
Does not work with current FireFox

### ISSUE THREAD

**Issue by Espilonarge** [RapidStrike/fa-filter#1]
As the title states, when Mozilla updated to FireFox Quantum, this script (including the Greasy Fork version) was broken entirely. There were a number of offensive artists I had blocked from my sight but without this script, their contents is plaguing my screen yet again.

**Comment by RapidStrike** [comment]
I'll take a look into this tonight.

**Comment by RapidStrike** [comment]
Turns out that the `GM_` prefix is deprecated and it forced everyone to make all `GM.getValue` calls asynchronous. As a quickfix, I wrapped everything in an async call, which is probably not a good idea, but it works!

Updated to version 1.5.5. @Espilonarge can you verify if it works now?

**Comment by Espilonarge** [comment]
Seems to be working now. :)
