### ISSUE TITLE
Filter button missing on classic theme

### ISSUE THREAD

**Issue by eaasye** [RapidStrike/fa-filter#2]
The filter user button and the "toggled filtered submissions" button both seem to be missing on the classic theme, but are working on the modern theme. Reinstalling the script didn't seem to fix anything either.

**Comment by RapidStrike** [comment]
Hi there, sorry for the late response.

I've updated the code to correctly detect the updated submissions code. Looks like FA was modernizing the classic layout as well. Please let me know if this works!

**Comment by RapidStrike** [comment]
Other users are reporting seeing the filters in the classic view now after the changes. Closing ticket.
